/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mostTiles_56 (
    input clk,
    input rst,
    input [24:0] grid,
    output reg [5:0] moreTiles
  );
  
  
  
  reg [4:0] M_compare_d, M_compare_q = 1'h0;
  
  always @* begin
    M_compare_d = M_compare_q;
    
    moreTiles = 1'h0;
    M_compare_d = grid[0+0-:1] + grid[1+0-:1] + grid[2+0-:1] + grid[3+0-:1] + grid[4+0-:1] + grid[5+0-:1] + grid[6+0-:1] + grid[7+0-:1] + grid[8+0-:1] + grid[9+0-:1] + grid[10+0-:1] + grid[11+0-:1] + grid[12+0-:1] + grid[13+0-:1] + grid[14+0-:1] + grid[15+0-:1] + grid[16+0-:1] + grid[17+0-:1] + grid[18+0-:1] + grid[19+0-:1] + grid[20+0-:1] + grid[21+0-:1] + grid[22+0-:1] + grid[23+0-:1] + grid[24+0-:1];
    moreTiles[0+0-:1] = (M_compare_q > 4'hc);
  end
  
  always @(posedge clk) begin
    M_compare_q <= M_compare_d;
  end
  
endmodule
